standingsrequests/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url

from . import views

app_name = "standingsrequests"

local_urlpatterns = [
    url(r"^$", views.index_view, name="index"),
    url(r"^create_requests", views.create_requests, name="create_requests"),
    url(r"^request_characters$", views.request_characters, name="request_characters"),
    url(
        r"^request_corporations$",
        views.request_corporations,
        name="request_corporations",
    ),
    url(
        r"^request_character_standing/(?P<character_id>\d+)/",
        views.request_character_standing,
        name="request_character_standing",
    ),
    url(
        r"^remove_character_standing/(?P<character_id>\d+)/",
        views.remove_character_standing,
        name="remove_character_standing",
    ),
    url(
        r"^request_corp_standing/(?P<corporation_id>\d+)/",
        views.request_corp_standing,
        name="request_corp_standing",
    ),
    url(
        r"^remove_corp_standing/(?P<corporation_id>\d+)/",
        views.remove_corp_standing,
        name="remove_corp_standing",
    ),
    url(r"^view/pilots/$", views.view_pilots_standings, name="view_pilots"),
    url(
        r"^view/pilots/json/$",
        views.view_pilots_standings_json,
        name="view_pilots_json",
    ),
    url(
        r"^view/pilots/download/$",
        views.download_pilot_standings,
        name="download_pilots",
    ),
    url(r"^view/corps/$", views.view_groups_standings, name="view_groups"),
    url(
        r"^view/corps/json$", views.view_groups_standings_json, name="view_groups_json"
    ),
    url(r"^manage/$", views.manage_standings, name="manage"),
    url(
        r"^manage/requests/$",
        views.manage_get_requests_json,
        name="manage_get_requests_json",
    ),
    # Should always follow the path of the GET path above
    url(
        r"^manage/requests/(?P<contact_id>\d+)/$",
        views.manage_requests_write,
        name="manage_requests_write",
    ),
    url(
        r"^manage/revocations/$",
        views.manage_get_revocations_json,
        name="manage_get_revocations_json",
    ),
    url(
        r"^manage/revocations/(?P<contact_id>\d+)/$",
        views.manage_revocations_write,
        name="manage_revocations_write",
    ),
    url(r"^view/requests/$", views.view_active_requests, name="view_requests"),
    url(
        r"^view/requests/json/$",
        views.view_requests_json,
        name="view_requests_json",
    ),
    url(r"^manage/setuptoken/$", views.view_auth_page, name="view_auth_page"),
    url(
        r"^requester_add_scopes/$",
        views.view_requester_add_scopes,
        name="view_requester_add_scopes",
    ),
    url(
        r"^admin_changeset_update_now/$",
        views.admin_changeset_update_now,
        name="admin_changeset_update_now",
    ),
]

urlpatterns = [
    url(r"^standingsrequests/", include((local_urlpatterns, "standingsrequests"))),
]

standingsrequests/templates/standingsrequests/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}

{% block page_title %}{% trans app_title %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        {% include 'standingsrequests/partials/_menu.html' %}
        <div class="col-lg-12 container">
            {% block page_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    {% include "standingsrequests/bundles/angular.html" %}
    <link rel="stylesheet" href="{% static 'standingsrequests/css/global.css' %}" type="text/css" media="screen">
{% endblock extra_css %}

standingsrequests/templates/standingsrequests/create_requests.html
{% extends "standingsrequests/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block page_content %}
    <p>
        On this page you can create requests to <strong>get standing</strong> or <strong>revoke standing</strong> with <strong>{{ organization.name }}</strong> for your alts. If you are missing an alt, please add it first on the dashboard.
    </p>

    <h3>{% trans "Your Characters" %}</h3>
    <div id="div_request_characters">
        {% include "standingsrequests/partials/_spinner.html" %}
        <br>
    </div>

    {% if corporations_enabled %}
        <h3>{% trans "Your Corporations" %}</h3>
        <div id="div_request_corporations">
            {% include "standingsrequests/partials/_spinner.html" %}
            <br>
        </div>
    {% endif %}

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans "Icon Legend" %}
            </div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <i class="fas fa-star fa-fw text-primary"></i>
                        </td>
                        <td>
                            {% trans "Character is in this organisation." %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fas fa-exclamation-triangle fa-fw text-warning"></i>
                        </td>
                        <td>
                            {% trans "The character / corporation has no standings from this organisation towards it." %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fas fa-hourglass-start fa-fw"></i>
                        </td>
                        <td>
                            {% trans "The standing has been requested and is pending action by a standings manager." %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fas fa-hourglass-half fa-fw text-success"></i>
                        </td>
                        <td>
                            {% trans "The request has been accepted by a standings manager, but is waiting for confirmation that those standings have been updated in game." %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fas fa-reply-all fa-fw text-danger"></i>
                        </td>
                        <td>
                            {% trans "The standing is being revoked by yourself, a standings manager or automatically if you no longer meet the requirements permitting blue standings access. It is pending confirmation." %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <i class="fas fa-info-circle fa-fw text-info"></i>
                        </td>
                        <td>
                            {% trans "More keys are required to request standing for this corporation." %}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}
    <script>
        $(function() {
            /* async load request_characters view into div or show HTTP errors if any */
            $("#div_request_characters").load(
                "{% url 'standingsrequests:request_characters' %}",
                function(responseTxt, statusTxt, xhr) {
                    if (statusTxt == "error") {
                        $("#div_request_characters").html(
                            '<p class="text-danger">{% trans "Failed to load content. Please reload this page to try again." %}</p>'
                        );
                    }
            });
            {% if corporations_enabled %}
                /* async load request_corporations view into div or show HTTP errors if any */
                $("#div_request_corporations").load(
                    "{% url 'standingsrequests:request_corporations' %}",
                    function(responseTxt, statusTxt, xhr) {
                        if (statusTxt == "error") {
                            $("#div_request_corporations").html(
                                '<p class="text-danger">{% trans "Failed to load content. Please reload this page to try again." %}</p>'
                            );
                        }
                });
            {% endif %}
        });
    </script>
{% endblock %}

standingsrequests/templates/standingsrequests/error.html
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block page_content %}
    <div class="col-lg-12 container">
        <div class="panel panel-danger">
          <div class="panel-heading">{% trans "Not yet initialized" %}</div>
          <div class="panel-body">
              This app has not yet been initiliazed. Please setup a token to start.
          </div>
        </div>
    </div>
{% endblock page_content %}

{% block extra_script %}
{% endblock extra_script %}

standingsrequests/templates/standingsrequests/manage.html
{% extends "standingsrequests/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'standingsrequests/css/manage.css' %}" type="text/css" media="screen">
{% endblock extra_css %}

{% block page_content %}
    <div ng-app="standingsApp" ng-controller="ManageStandingsController">
        <error-messages></error-messages>

        <!-- Requests -->

        <h2 style="margin-top:0;">
            {% trans "Pending Requests" %} ({{requests_count|default:"-"}})
        </h2>
        <p>Standing requests with pending action for <strong>{{organization.name}}</strong></p>
        <div class="container-fluid">

            <div id="div_spinner_requests" class="row">
                <div>
                    {% include "standingsrequests/partials/_spinner.html" %}
                </div>
            </div>

            <div id="div_requests" class="row" style="visibility: hidden">
                <div class="table-responsive">
                    <table id="tab_requests" class="table table-condensed table-hover table-striped">
                        <tr>
                            <th class="col-md-1">{% trans "Date" %}</th>
                            <th class="col-md-2">{% trans "Contact Name" %}</th>
                            <th class="col-md-2">{% trans "Corporation / Alliance" %}</th>
                            <th class="col-md-2">{% trans "Main Character" %}</th>
                            <th class="col-md-3">{% trans "Scopes / State" %}</th>
                            <th class="col-md-2">{% trans "Actions" %}</th>
                        </tr>
                        {% verbatim %}
                        <tr ng-repeat="contact in requests">
                            <td>
                                {{ contact.request_date | date:'yyyy-MM-dd HH:mm' }}
                            </td>
                            <td>
                                <img ng-src="{{ contact.contact_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                <span class="copy_to_clipboard" data-text="{{ contact.contact_name }}">
                                    {{ contact.contact_name }}&nbsp;<i class="far fa-copy"></i>
                                </span>
                            </td>
                            <td>
                                <span ng-show="contact.corporation_ticker">
                                    [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                                </span><br>
                                <span ng-show="contact.alliance_name" ng-bind="contact.alliance_name"></span>
                            </td>
                            <td>
                                <img ng-src="{{ contact.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                <span ng-show="contact.main_character_ticker">
                                    [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                                </span>
                            </td>
                            <td>
                                <bool-checkmark value="contact.has_scopes" true-title="Has required scopes" false-title="Missing Scopes add then using Add Scopes"></bool-checkmark>
                                {{contact.state}}
                            </td>
                            <td>
                                <button class="btn btn-success" ng-click="actionRequest(contact)" title="Confirm the standing was ADDED in game">
                                    Confirm
                                </button>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <button class="btn btn-danger" ng-click="rejectRequest(contact)" title="Reject this standing request">
                                    Reject
                                </button>

                            </td>
                        </tr>

                        <tr ng-hide="requests.length > 0">
                            <td class="text-muted" colspan="9" style="text-align: left; vertical-align: middle;">
                                Empty
                            </td>
                        </tr>

                        {% endverbatim %}
                    </table>
                </div>
            </div>
        </div>

        <!-- Revocations -->

        <h2 style="margin-top:0;">
            {% trans "Pending Revocations" %} ({{revocations_count|default:"-"}})
        </h2>
        <p>Standing revocations with pending action for <strong>{{organization.name}}</strong></p>
        <div class="container-fluid">

            <div id="div_spinner_revocations" class="row">
                <div>
                    {% include "standingsrequests/partials/_spinner.html" %}
                </div>
            </div>

            <div id="div_revocations" class="row" style="visibility: hidden">
                <div class="table-responsive">
                    <table id="tab_revocations" class="table table-condensed table-hover table-striped">
                        <tr>
                            <th class="col-md-1">{% trans "Date" %}</th>
                            <th class="col-md-2">{% trans "Contact Name" %}</th>
                            <th class="col-md-2">{% trans "Corporation / Alliance" %}</th>
                            <th class="col-md-2">{% trans "Main Character" %}</th>
                            <th class="col-md-1">{% trans "Scopes / State" %}</th>
                            <th class="col-md-2">{% trans "Reason / Contact Labels" %}</th>
                            <th class="col-md-2">{% trans "Actions" %}</th>
                        </tr>
                        {% verbatim %}
                        <tr ng-repeat="contact in revocations">
                            <td>
                                {{ contact.request_date | date:'yyyy-MM-dd HH:mm' }}
                            </td>
                            <td>
                                <img ng-src="{{ contact.contact_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                <span class="copy_to_clipboard" data-text="{{ contact.contact_name }}">
                                    {{ contact.contact_name }}&nbsp;<i class="far fa-copy"></i>
                                </span>
                            </td>
                            <td>
                                <span ng-show="contact.corporation_ticker">
                                    [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                                </span><br>
                                <span ng-show="contact.alliance_name" ng-bind="contact.alliance_name"></span>
                            </td>
                            <td>
                                <img ng-src="{{ contact.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                <span ng-show="contact.main_character_name">
                                    [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                                </span>

                            </td>
                            <td>
                                <bool-checkmark value="contact.has_scopes" true-title="Has required scopes" false-title="Missing Scopes add then using Add Scopes"></bool-checkmark>
                                {{ contact.state }}
                            </td>
                            <td>
                                {{ contact.reason }}<br>
                                <div ng-repeat="obj in contact.labels">{{ obj }}<span ng-if="!$last">, </span></div>
                            </td>
                            <td>
                                <button class="btn btn-success" ng-click="actionRevocation(contact)" title="Confirm the standing was REMOVED in game">
                                    Confirm
                                </button>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <button class="btn btn-danger" ng-click="deleteRevocation(contact)" title="Reject this revocation request">
                                    Reject
                                </button>
                            </td>
                        </tr>

                        <tr ng-hide="revocations.length > 0">
                            <td class="text-muted" colspan="9" style="text-align: left; vertical-align: middle;">
                                Empty
                            </td>
                        </tr>

                        {% endverbatim %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standingsrequests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standingsrequests/app.js' %}"></script>
    <script src="{% static 'standingsrequests/error.js' %}"></script>
    <script src="{% static 'standingsrequests/standings_filter.js' %}"></script>
    <script src="{% static 'standingsrequests/manage.js' %}"></script>

    <script type="text/javascript">
        function copyToClipboard(text) {
            if (window.clipboardData && window.clipboardData.setData) {
                // IE specific code path to prevent textarea being shown while dialog is visible.
                return clipboardData.setData("Text", text);

            } else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
                var textarea = document.createElement("textarea");
                textarea.textContent = text;
                textarea.style.position = "fixed";  // Prevent scrolling to bottom of page in MS Edge.
                document.body.appendChild(textarea);
                textarea.select();
                try {
                    return document.execCommand("copy");  // Security exception may be thrown by some browsers.
                } catch (ex) {
                    console.warn("Copy to clipboard failed.", ex);
                    return false;
                } finally {
                    document.body.removeChild(textarea);
                }
            }
        }

        $(document).ready(function () {
            $('#tab_requests').on('click', '.copy_to_clipboard', function (event) {
                var text = event.currentTarget.getAttribute("data-text")
                copyToClipboard(text)
            });
            $('#tab_revocations').on('click', '.copy_to_clipboard', function (event) {
                var text = event.currentTarget.getAttribute("data-text")
                copyToClipboard(text)
            });
        });
    </script>
{% endblock extra_javascript %}

standingsrequests/templates/standingsrequests/requests.html
{% extends "standingsrequests/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block page_content %}
    <div ng-app="standingsApp" ng-controller="ViewRequestsController">
        <error-messages></error-messages>

        <!-- Requests -->

        <h2 style="margin-top:0;">
            {% trans "Effective Requests" %} ({{requests_count|default:"-"}})
        </h2>
        <p>All effective standing requests for <strong>{{organization.name}}</strong></p>
        <div class="container-fluid">

            <div id="div_spinner" class="row">
                <div class="col-md-12">
                    {% include "standingsrequests/partials/_spinner.html" %}
                </div>
            </div>

            <div id="div_requests" class="row" style="visibility: hidden">
                <div class="table-responsive">
                    <table class="table table-condensed table-hover table-striped">
                        <tr>
                            <th class="col-md-1">{% trans "Date" %}</th>
                            <th class="col-md-2">{% trans "Contact Name" %}</th>
                            <th class="col-md-2">{% trans "Corporation / Alliance" %}</th>
                            <th class="col-md-2">{% trans "Main Character" %}</th>
                            <th class="col-md-1">{% trans "Scopes / State" %}</th>
                            <th class="col-md-2">{% trans "Effective / Accepted By" %}</th>
                            <th class="col-md-2">{% trans "Contact Labels" %}</th>
                        </tr>
                        {% verbatim %}
                        <tr ng-repeat="contact in requests">
                            <td>
                                {{ contact.request_date | date:'yyyy-MM-dd HH:mm' }}
                            </td>
                            <td>
                                <img ng-src="{{ contact.contact_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                {{ contact.contact_name }}
                            </td>
                            <td>
                                <span ng-show="contact.corporation_ticker">
                                    [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                                </span><br>
                                <span ng-show="contact.alliance_name" ng-bind="contact.alliance_name"></span>
                            </td>
                            <td>
                                <img ng-src="{{ contact.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                <span ng-show="contact.main_character_ticker">
                                    [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                                </span>
                            </td>
                            <td>
                                <bool-checkmark value="contact.has_scopes" true-title="Has required scopes" false-title="Missing required scopes"></bool-checkmark>
                                {{contact.state}}
                            </td>
                            <td>
                                <bool-checkmark value="contact.is_effective" true-title="Standing Effective" false-title="Standing not effective"></bool-checkmark>
                                <span ng-bind="contact.action_by" ng-show="contact.action_by"></span>
                            </td>
                            <td>
                                <div ng-repeat="obj in contact.labels">{{ obj }}<span ng-if="!$last">, </span></div>
                            </td>
                        </tr>

                        <tr ng-hide="requests.length > 0">
                            <td class="text-muted" colspan="10" style="text-align: center; vertical-align: middle;">
                            Empty
                            </td>
                        </tr>

                        {% endverbatim %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standingsrequests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standingsrequests/app.js' %}"></script>
    <script src="{% static 'standingsrequests/error.js' %}"></script>
    <script src="{% static 'standingsrequests/standings_filter.js' %}"></script>
    <script src="{% static 'standingsrequests/manage.js' %}"></script>
    <script src="{% static 'standingsrequests/requests.js' %}"></script>
{% endblock extra_javascript %}

standingsrequests/templates/standingsrequests/view_pilots.html
{% extends "standingsrequests/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block page_content %}
    <div ng-app="standingsApp" ng-controller="PilotListController">
        <standings-filter-controls states="true" scopes="false"></standings-filter-controls>
        <div class="col-lg-12 container">
            <h2 class="page-header">
                {% trans "Characters" %} ({{pilots_count|default:"-"}})
                {% if perms.standingstool.download %}
                    <div class="pull-right">
                        <a href="{% url 'standingsrequests:download_pilots' %}" class="btn btn-default">
                            {% trans "Download" %}
                        </a>
                    </div>
                {% endif %}
            </h2>
            {% include "standingsrequests/partials/_contacts_legend.html" %}
            <div class="pull-right form-inline">
                <div class="form-group" style="padding-bottom:1.9em;">
                    <label for="userPageSize">Page size</label>
                    <select id="userPageSize" type="text" ng-model="pageSize" class="form-control" style="width:5em;">
                        <option value="10">10</option>
                        <option value="50" selected>50</option>
                        <option value="100">100</option>
                        <option value="500">500</option>
                        <option value="1000">1000</option>
                        <option value="">Everything</option>
                    </select>
                </div>
                <ul uib-pagination total-items="filteredStandings.length" ng-model="currentPage" max-size="5"
                    boundary-link-numbers="true" boundary-links="true" style="margin:0;"
                    items-per-page="pageSize"
                    previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;"></ul>
            </div>
            <div class="col-lg-12 container">

                 <div id="div_spinner" class="row">
                    <div class="col-md-12">
                        {% include "standingsrequests/partials/_spinner.html" %}
                    </div>
                </div>

                <div id="div_results" class="row" style="visibility: hidden">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-striped">
                            <tr>
                                <th class="col-md-2">{% trans "Character" %}</th>
                                <th class="col-md-2">{% trans "Corporation" %}</th>
                                <th class="col-md-2">{% trans "Alliance" %}</th>
                                <th class="col-md-1">{% trans "Faction" %}</th>
                                <th class="col-md-1">{% trans "Standing" %}</th>
                                <th class="col-md-1">{% trans "Labels" %}</th>
                                <th class="col-md-2">{% trans "Main Character" %}</th>
                                <th class="col-md-1">{% trans "State" %}</th>
                            </tr>
                            {% verbatim %}
                            <tr ng-repeat="character in filteredStandings = (pilots | filterStandings) | limitTo : pageSize : (currentPage-1) * pageSize as pilotsFiltered">
                                <td>
                                    <img ng-src="{{ character.character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                    {{ character.character_name }}
                                </td>
                                <td>
                                    <span ng-show="character.corporation_ticker">
                                        [{{ character.corporation_ticker }}]
                                    </span>
                                    <span ng-show="character.corporation_name">
                                        {{ character.corporation_name }}
                                    </span>
                                </td>
                                <td>
                                    <span ng-show="character.alliance_name" ng-bind="character.alliance_name"></span>
                                </td>
                                <td>
                                    <span ng-show="character.faction_name" ng-bind="character.faction_name"></span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em;">
                                        <standings-icon standing="character.standing"></standings-icon>
                                    </span>
                                </td>
                                <td>
                                    <span ng-repeat="label in character.labels | orderBy">
                                        {{ label }}
                                        <span ng-show="!$last">,&nbsp;</span>
                                    </span>
                                </td>
                                <td>
                                    <img ng-src="{{ character.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                                    <span ng-show="character.main_character_ticker">
                                        [{{ character.main_character_ticker }}]
                                    </span>
                                    <span ng-show="character.main_character_name">
                                        {{ character.main_character_name }}
                                    </span>
                                </td>
                                <td>
                                    {{character.state}}
                                </td>
                            </tr>

                            <tr ng-hide="pilotsFiltered.length > 0">
                                <td class="text-muted" colspan="8" style="text-align: left; vertical-align: middle;">
                                Empty
                                </td>
                            </tr>

                            {% endverbatim %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standingsrequests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standingsrequests/app.js' %}"></script>
    <script src="{% static 'standingsrequests/standings_filter.js' %}"></script>
    <script src="{% static 'standingsrequests/view_pilots.js' %}"></script>
{% endblock extra_javascript %}