standingsrequests/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url

from . import views

app_name = "standingsrequests"

local_urlpatterns = [
    url(r"^$", views.index_view, name="index"),
    url(r"^create_requests", views.create_requests, name="create_requests"),
    url(r"^request_characters$", views.request_characters, name="request_characters"),
    url(
        r"^request_corporations$",
        views.request_corporations,
        name="request_corporations",
    ),
    url(
        r"^request_character_standing/(?P<character_id>\d+)/",
        views.request_character_standing,
        name="request_character_standing",
    ),
    url(
        r"^remove_character_standing/(?P<character_id>\d+)/",
        views.remove_character_standing,
        name="remove_character_standing",
    ),
    url(
        r"^request_corp_standing/(?P<corporation_id>\d+)/",
        views.request_corp_standing,
        name="request_corp_standing",
    ),
    url(
        r"^remove_corp_standing/(?P<corporation_id>\d+)/",
        views.remove_corp_standing,
        name="remove_corp_standing",
    ),
    url(r"^view/pilots/$", views.view_pilots_standings, name="view_pilots"),
    url(
        r"^view/pilots/json/$",
        views.view_pilots_standings_json,
        name="view_pilots_json",
    ),
    url(
        r"^view/pilots/download/$",
        views.download_pilot_standings,
        name="download_pilots",
    ),
    url(r"^view/corps/$", views.view_groups_standings, name="view_groups"),
    url(
        r"^view/corps/json$", views.view_groups_standings_json, name="view_groups_json"
    ),
    url(r"^manage/$", views.manage_standings, name="manage"),
    url(
        r"^manage/requests/$",
        views.manage_get_requests_json,
        name="manage_get_requests_json",
    ),
    # Should always follow the path of the GET path above
    url(
        r"^manage/requests/(?P<contact_id>\d+)/$",
        views.manage_requests_write,
        name="manage_requests_write",
    ),
    url(
        r"^manage/revocations/$",
        views.manage_get_revocations_json,
        name="manage_get_revocations_json",
    ),
    url(
        r"^manage/revocations/(?P<contact_id>\d+)/$",
        views.manage_revocations_write,
        name="manage_revocations_write",
    ),
    url(r"^view/requests/$", views.view_active_requests, name="view_requests"),
    url(
        r"^view/requests/json/$",
        views.view_requests_json,
        name="view_requests_json",
    ),
    url(r"^manage/setuptoken/$", views.view_auth_page, name="view_auth_page"),
    url(
        r"^requester_add_scopes/$",
        views.view_requester_add_scopes,
        name="view_requester_add_scopes",
    ),
    url(
        r"^admin_changeset_update_now/$",
        views.admin_changeset_update_now,
        name="admin_changeset_update_now",
    ),
]

urlpatterns = [
    url(r"^standingsrequests/", include((local_urlpatterns, "standingsrequests"))),
]

standingsrequests/templates/standingsrequests/partials/_angular_urls.html
{% load static %}
var urls = {
    pilots_json: "{% url 'standingsrequests:view_pilots_json' %}",
    groups_json: "{% url 'standingsrequests:view_groups_json' %}",
    standings_icon_template: "{% static 'standingsrequests/templates/standing.html' %}",
    standings_filter_controls_template: "{% static 'standingsrequests/templates/standings_filters.html' %}",
    copy_field_template: "{% static 'standingsrequests/templates/copy_field.html' %}",
    standings_requests_json_base: "{% url 'standingsrequests:manage_get_requests_json' %}",
    standings_revocations_json_base: "{% url 'standingsrequests:manage_get_revocations_json' %}",
    bool_tick_template: "{% static 'standingsrequests/templates/bool_tick.html' %}",
    error_template: "{% static 'standingsrequests/templates/error.html' %}",
    view_requests_json_base: "{% url 'standingsrequests:view_requests_json' %}",
};

standingsrequests/templates/standingsrequests/partials/_contacts_legend.html
<p>
    Current in-game contacts with standings from <strong>{{ organization.name }}</strong><br/>
    This data was last updated at: {{ lastUpdate | date:"SHORT_DATETIME_FORMAT" }}
</p>

standingsrequests/templates/standingsrequests/partials/_menu.html
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'standingsrequests:index' %}">{% trans app_title %}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'standingsrequests:create_requests' %}">
                    <a href="{% url 'standingsrequests:create_requests' %}">{% trans "Create Requests" %}</a>
                </li>

                 {% if perms.standingsrequests.affect_standings %}
                <li class="{% navactive request 'standingsrequests:manage' %}">
                    <a href="{% url 'standingsrequests:manage' %}">
                        {% trans "Manage Requests" %}
                        {% if pending_total_count > 0 %}
                            &nbsp;<span class="badge badge-nav">{{ pending_total_count }}</span>
                        {% endif %}
                    </a>
                </li>
                <li class="{% navactive request 'standingsrequests:view_requests' %}">
                    <a href="{% url 'standingsrequests:view_requests' %}">{% trans "Effective Requests" %}</a>
                </li>
                {% endif %}

                {% if perms.standingsrequests.view %}
                <li class="{% navactive request 'standingsrequests:view_pilots' %}">
                    <a href="{% url 'standingsrequests:view_pilots' %}">{% trans "Character Standings" %}</a>
                </li>
                <li class="{% navactive request 'standingsrequests:view_groups' %}">
                    <a href="{% url 'standingsrequests:view_groups' %}">{% trans "Group Standings" %}</a>
                </li>
                {% endif %}
            </ul>
             <ul class="nav navbar-nav navbar-right">
                {% if perms.standingsrequests.affect_standings %}
                    <a class="btn btn-default navbar-btn" href="{% url 'standingsrequests:view_auth_page' %}">
                        {% if operation_mode == "corporation" %}
                            {% trans "Setup Corporation Token" %}
                        {% else %}
                            {% trans "Setup Alliance Token" %}
                        {% endif %}
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

standingsrequests/templates/standingsrequests/partials/_request_characters.html
{% load static %}
{% load i18n %}
{% load evelinks %}

<div class="container-fluid">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-condensed table-hover table-striped">
                <tr>
                    <th class="col-md-2">{% trans "Character" %}</th>
                    <th class="col-md-2">{% trans "Corporation" %}</th>
                    <th class="col-md-2">{% trans "Alliance" %}</th>
                    <th class="col-md-1">{% trans "Scopes" %}</th>
                    <th class="col-md-1">{% trans "Standing" %}</th>
                    <th class="col-md-1">{% trans "Actions" %}</th>
                </tr>
                {% for std in characters %}
                    <tr>
                        <td>
                            <img src="{{ std.character|character_portrait_url:32 }}" class="img-circle">&nbsp;&nbsp;&nbsp;{{ std.character.character_name }}
                        </td>
                        <td>
                            [{{ std.character.corporation_ticker }}] {{ std.character.corporation_name }}
                        </td>
                        <td>
                            {{ std.character.alliance_name|default_if_none:"" }}
                        </td>
                        <td>
                            <span style="font-size:2em;">
                                {% if std.hasRequiredScopes %}
                                    <i class="fas fa-check fa-fw text-success" title="Has required scopes"></i>
                                {% else %}
                                    <a title="{% trans 'Add required scopes' %}" class="btn btn-danger btn-sm" href="{% url 'standingsrequests:view_requester_add_scopes' %}"><i class="fas fa-plus"></i> {% trans "Required" %}</a>
                                {% endif %}
                            </span>
                        </td>
                        <td>
                            <p>
                                <span style="font-size:2em;">
                                    {% if std.inOrganisation == True %}
                                        <i class="fas fa-star fa-fw text-primary" title="{% trans 'In Organisation' %}"></i>
                                    {% elif std.requestActioned == True %}
                                        <i class="fas fa-hourglass-half fa-fw text-success" title="{% trans 'Accepted, pending update in game.' %}"></i>
                                    {% elif std.pendingRequest == True %}
                                        <i class="fas fa-hourglass-start fa-fw" title="{% trans 'Standing Pending' %}"></i>
                                    {% elif std.pendingRevocation == True %}
                                        <i class="fas fa-reply-all fa-fw text-danger" title="{% trans 'Standing is being revoked' %}"></i>
                                    {% elif std.standing == None and std.pendingRequest == False %}
                                        <i class="fas fa-exclamation-triangle text-warning" title="{% trans 'No Standing' %}"></i>
                                    {% else %}
                                        {% include 'standingsrequests/partials/_standing.html' with standing=std.standing %}
                                    {% endif %}
                                </span>
                            </p>
                        </td>
                        <td>
                            <p>
                                <span style="font-size:2em;">
                                    {% if std.inOrganisation == True %}
                                        <!-- Already in organisation, No actions -->
                                    {% elif std.pendingRequest == True or std.requestActioned == True %}
                                        <a
                                            class="btn btn-warning"
                                            role="button"
                                            href="{% url 'standingsrequests:remove_character_standing' character_id=std.character.character_id %}"
                                            title="Cancel Request">
                                            Cancel
                                        </a>
                                    {% elif std.pendingRevocation == True %}
                                        <!-- Revoked, No actions -->
                                    {% elif not std.hasStanding %}
                                        <a
                                            class="btn btn-primary"
                                            role="button"
                                            href="{% url 'standingsrequests:request_character_standing' character_id=std.character.character_id %}"
                                            title="Request to get standing for this character"
                                            {% if not std.hasRequiredScopes %}
                                            disabled
                                            {% endif %}
                                            >
                                            &nbsp;Apply&nbsp;
                                        </a>
                                    {% else %}
                                        <a
                                            class="btn btn-danger"
                                            role="button"
                                            href="{% url 'standingsrequests:remove_character_standing' character_id=std.character.character_id %}"
                                            title="Request to revoke standing for this character">
                                            Revoke
                                        </a>
                                    {% endif %}
                                </span>
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

standingsrequests/templates/standingsrequests/partials/_request_corporations.html
{% load static %}
{% load i18n %}
{% load evelinks %}

<div class="container-fluid">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-condensed table-hover table-striped">
                <tr>
                    <th class="col-md-4">{% trans "Corporation" %}</th>
                    <th class="col-md-2">{% trans "Alliance" %}</th>
                    <th class="col-md-1">{% trans "Keys/Req" %}</th>
                    <th class="col-md-1">{% trans "Standing" %}</th>
                    <th class="col-md-1">{% trans "Actions" %}</th>
                </tr>
                {% for st in corps %}
                    <tr>
                        <td>
                            <img src="{{ st.corp.corporation_id|corporation_logo_url:32 }}" class="img-circle">
                            &nbsp;&nbsp;&nbsp;
                            {{ st.corp.corporation_name }}
                        </td>
                        <td>
                            {{ st.corp.alliance_name|default_if_none:"" }}
                        </td>
                        <td>
                            {{ st.token_count }}/{{ st.corp.member_count }}
                        </td>
                        <td>
                            <p>
                                <span style="font-size:2em;">
                                    {% if st.inOrganisation == True %}
                                        <i class="fas fa-star fa-fw text-primary" title="{% trans 'In Organisation' %}"></i>
                                    {% elif st.requestActioned == True %}
                                        <i class="fas fa-hourglass-half fa-fw text-success" title="{% trans 'Accepted, pending update in game.' %}"></i>
                                    {% elif st.pendingRequest == True %}
                                        <i class="fas fa-hourglass-start fa-fw" title="{% trans 'Standing Pending' %}"></i>
                                    {% elif st.pendingRevocation == True %}
                                        <i class="fas fa-reply-all fa-fw text-danger" title="{% trans 'Standing is being revoked' %}"></i>
                                    {% elif st.standing == None and st.pendingRequest == False %}
                                        <i class="fas fa-exclamation-triangle text-warning" title="{% trans 'No Standing' %}"></i>
                                    {% else %}
                                        {% include 'standingsrequests/partials/_standing.html' with standing=st.standing %}
                                    {% endif %}
                                </span>
                            </p>
                        </td>
                        <td>
                            <p>
                                <span style="font-size:2em;">
                                    {% if st.pendingRequest == True or st.requestActioned == True %}
                                        <a
                                            class="btn btn-warning"
                                            role="button"
                                            href="{% url 'standingsrequests:remove_corp_standing' corporation_id=st.corp.corporation_id %}"
                                            title="Cancel Request">
                                            Cancel
                                        </a>
                                    {% elif st.pendingRevocation == True %}
                                        <!-- Revoked, No actions -->
                                    {% elif not st.hasStanding %}
                                        {% if st.token_count >= st.corp.member_count %}
                                            <a
                                                class="btn btn-primary"
                                                role="button"
                                                href="{% url 'standingsrequests:request_corp_standing' corporation_id=st.corp.corporation_id %}"
                                                title="Request to get standing for this corporation">
                                                &nbsp;Apply&nbsp;
                                            </a>
                                        {% else %}
                                            <i class="fas fa-info-circle text-info" title="{% trans 'More keys required to request standings' %}"></i>
                                        {% endif %}
                                    {% else %}
                                        <a
                                            class="btn btn-danger"
                                            role="button"
                                            href="{% url 'standingsrequests:remove_corp_standing' corporation_id=st.corp.corporation_id %}"
                                            title="Request to revoke standing for this corporation">
                                            Revoke
                                        </a>
                                    {% endif %}
                                </span>
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

standingsrequests/templates/standingsrequests/partials/_spinner.html
{% load static %}

{% if NIGHT_MODE %}
    <img src="{% static 'standingsrequests/img/Spinner-1s-64px-dark.gif' %}" alt="Spinner"/>
{% else %}
    <img src="{% static 'standingsrequests/img/Spinner-1s-64px-light.gif' %}" alt="Spinner"/>
{% endif %}
Loading...

standingsrequests/templates/standingsrequests/partials/_standing.html
{% if standing < -5.0 %}
    <i class="fas fa-minus-square fa-fw" style="color:#930404;" title="{{ standing }}"></i>
{% elif standing < 0.0 %}
    <i class="fas fa-minus-square fa-fw" style="color:#c34704;" title="{{ standing }}"></i>
{% elif standing == 0.0 %}
    &nbsp;<i class="fas fa-equals fa-fw" style="background:#878787; color:white; font-size:75%" title="{{ standing }}"></i>
{% elif standing <= 5.0 %}
    <i class="fas fa-plus-square fa-fw" style="color:#2a64c3;" title="{{ standing }}"></i>
{% elif standing <= 10.0 %}
    <i class="fas fa-plus-square fa-fw" style="color:#042177;" title="{{ standing }}"></i>
{% endif %}

standingsrequests/templates/standingsrequests/partials/_view_groups_alliances.html
{% load i18n %}

<h3>{% trans "Alliances" %}</h3>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <tr>
            <th class="col-md-6">{% trans "Name" %}</th>
            <th class="col-md-1">{% trans "Standing" %}</th>
            <th class="col-md-5">{% trans "Labels" %}</th>
        </tr>
        {% verbatim %}
        <!-- Should DRY this -->
        <tr ng-repeat="entity in alliances | filterStandings as alliancesFiltered">
                <td>
                <img ng-src="{{ entity.alliance_icon_url }}" class="img-circle"/>&nbsp;&nbsp;{{ entity.alliance_name }}
            </td>
            <td>
                <span style="font-size:1.5em;">
                    <standings-icon standing="entity.standing"></standings-icon>
                </span>
            </td>
            <td>
                <span ng-repeat="label in entity.labels | orderBy">
                    {{ label }}
                    <span ng-show="!$last">,&nbsp;</span>
                </span>
            </td>
        </tr>

        <tr ng-hide="alliancesFiltered.length > 0">
            <td class="text-muted" colspan="3" style="text-align: left; vertical-align: middle;">
            Empty
            </td>
        </tr>

        {% endverbatim %}
    </table>
</div>

standingsrequests/templates/standingsrequests/partials/_view_groups_corporations.html
{% load i18n %}

<h3>{% trans "Corporations" %}</h3>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped">
        <tr>
            <th class="col-md-2">{% trans "Name" %}</th>
            <th class="col-md-2">{% trans "Alliance" %}</th>
            <th class="col-md-2">{% trans "Faction" %}</th>
            <th class="col-md-1">{% trans "Standing" %}</th>
            <th class="col-md-2">{% trans "Labels" %}</th>
            <th class="col-md-2">{% trans "Main Character" %}</th>
            <th class="col-md-1">{% trans "State" %}</th>
        </tr>
        {% verbatim %}
        <tr ng-repeat="entity in corps | filterStandings as corpsFiltered">
            <td>
                <img ng-src="{{ entity.corporation_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                {{ entity.corporation_name }}
            </td>
            <td>
                {{ entity.alliance_name }}
            </td>
            <td>
                {{ entity.faction_name }}
            </td>
            <td>
                <span style="font-size:1.5em;">
                    <standings-icon standing="entity.standing"></standings-icon>
                </span>
            </td>
            <td>
                <span ng-repeat="label in entity.labels | orderBy">
                    {{ label }}
                    <span ng-show="!$last">,&nbsp;</span>
                </span>
            </td>
            <td>
                <img ng-src="{{ entity.main_character_icon_url }}" class="img-circle"/>&nbsp;&nbsp;
                <span ng-show="entity.main_character_ticker">
                    [{{ entity.main_character_ticker }}]
                </span>
                <span ng-show="entity.main_character_name">
                    {{ entity.main_character_name }}
                </span>
            </td>
            <td>
                {{entity.state}}
            </td>
        </tr>

        <tr ng-hide="corpsFiltered.length > 0">
            <td class="text-muted" colspan="3" style="text-align: left; vertical-align: middle;">
            Empty
            </td>
        </tr>
        {% endverbatim %}

    </table>
</div>